name: hsdoc
version: 0.1.0.0
license: GPL-3.0-or-later

extra-source-files:
  - README.md
  - ChangeLog.md

description: Write document in haskell

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
